[package]
name = "dsl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swayipc = "3.0.1"
dbus-crossroads = "0.5.2"
dbus = "0.9.7"
lazy_static = "1.4.0"
async-priority-channel = "0.1.0"
